development:
  access_key_id: AKIAIAJBXKOK7N5UDVDA
  secret_access_key: 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
  region: us-east-1
  s3_host_name: s3-eu-west-1.amazonaws.com

production:
  access_key_id: AWS_ACCESS_KEY_ID
  secret_access_key: AWS_SECRET_KEY_ID
  region: us-east-1
  s3_host_name: s3-eu-west-1.amazonaws.com


#https://s3-eu-west-1.amazonaws.com/vladibucket/recipes/images/000/000/002/small/DSC03940.jpg